name: Makie CI
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'
    branches:
      - master
      - breaking-release
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
    branches:
      - master
      - breaking-release
    tags: '*'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Julia 1.8
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        run: sudo apt-get -y install xclip
      - uses: julia-actions/cache@v1
      - name: Install Julia dependencies
        shell: julia --project=monorepo {0}
        run: |
          using Pkg;
          # dev mono repo versions
          pkg"dev . ./MakieCore"
          Pkg.test("Makie"; coverage=true)

      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
